name: Build pipeline

on: 
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout flow
        uses: actions/checkout@v4
        with: 
          node-version: '18'

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: npm install

      - name: Run build
        uses: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact
        with: 
          name: build-artifact
          path: build/
        
